# Generated by Django 4.1.1 on 2022-11-07 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marcas', '0003_marca_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marca',
            name='user',
        ),
    ]
